// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxv5Hr5jV8LV6vX4o9sCYIObFDAlIXcHo',
    appId: '1:707741483847:android:eaf67b53f4b52411250262',
    messagingSenderId: '707741483847',
    projectId: 'gocorona-405f5',
    storageBucket: 'gocorona-405f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfYxJXkITg4uPwnUqGQ4ux4Ti0fJ_R3dE',
    appId: '1:707741483847:ios:165d8d62eeb1520d250262',
    messagingSenderId: '707741483847',
    projectId: 'gocorona-405f5',
    storageBucket: 'gocorona-405f5.appspot.com',
    androidClientId: '707741483847-3ve09jluitr9rc8n58k5c1b07u499d25.apps.googleusercontent.com',
    iosClientId: '707741483847-ul8rov7t0mic5ai0le78sr0t72fnaht6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomGetx',
  );
}
